Assignment operators generator
szeged/js-test-generators pull request #11
Opened 2018-11-29 14:46 UTC by matedabis

It only differs from binary operators generator in the string creator method, the '=' operator,
the init function, and the expression generator.

2018-12-04 14:46 UTC, matedabis commented
Updated and synchronized with #2

2018-12-04 16:46 UTC, rerobika reviewed
The code looks much cleaner. Could you show me an output?

2018-12-05 07:17 UTC, matedabis commented
@rerobika 
```
function validate_numeric(test_value, expected_result, false_results) {
    var radix = 2 + Math.abs(expected_result % 35);
    assert(test_value === expected_result);
    assert(test_value.toString(radix) === expected_result.toString(radix));
    for (var i in false_results) {
        radix = 2 + Math.abs(false_results[i] % 35);
        assert(test_value !== false_results[i]);
        assert(test_value.toString(radix) !== false_results[i].toString(radix));
    }
}

t1 = 1045528973;
t2 = 611824280;
t3 = -1004050318;
t4 = 37311241;
t5 = 894504598;
t6 = 0;
t7 = 322296;
t8 = -1460585667;
t9 = 1300624934;
t10 = 115189529;
f1 = 718954894;
f2 = 1812465500;
f3 = 717150757;
f4 = 940592135;
f5 = -2022053499;
e = 115189529;
t1 &= t2; t1 >>= t3; t1 ^= t4; t1 |= t5; t1 <<= t6; t1 |= t7; t1 >>= t8; t1 &= t9; t1 ^= t10; 
validate_numeric(t1, e, [f1, f2, f3, f4, f5]);

...
```

2018-12-05 09:04 UTC, rerobika requested changes
Getting close.

2018-12-05 09:04 UTC, rerobika commented on src/scripts/generate_assignments.py
> +                calculation += ("%s %s= %s; " % (self.TEST_VALUE_VAR_NAME.format(NUMBER = 1), result["oper"],
Could we put a new line after each declaration?

2018-12-05 09:04 UTC, rerobika commented on src/scripts/generate_assignments.py
> +        return {'oper': '=', 'op2': op2, 'sum': sum}
Why `sum` is needed?

```py
return {'oper': '=', 'op2': op2, 'sum': 'op2'}
```

Isn't this an equivalent solution?

2018-12-05 09:04 UTC, rerobika commented on src/scripts/generate_assignments.py
> +                calculation += ("%s %s %s; " % (self.TEST_VALUE_VAR_NAME.format(NUMBER = 1), result["oper"],
This statement is really similar to the statement below.

How about?
```py
calculation += ("%s %s %s %s\n; " % (self.TEST_VALUE_VAR_NAME.format(NUMBER = 1), result["oper"], "" if (result["oper"] == "=") else "=", self.TEST_VALUE_VAR_NAME.format(NUMBER = (i + 2))))
```

2018-12-06 07:43 UTC, rerobika commented
The patch seems OK for me right now, but #2 must land first.

2019-01-24 13:11 UTC, loki04 approved these changes
LGTM after #2

2019-01-25 06:43 UTC, rerobika approved these changes
LGTM

2019-01-25 06:44 UTC, merged